### ISSUE TITLE
[Feature request] Add global pre-alignment of burst images

### ISSUE THREAD

**Issue by chris-rank** [martin-marek/hdr-plus-swift#10]
I would suggest to add a global pre-alignment step before the tile-based alignment starts. The tile-based alignment could then be initialized with the values of the global pre-alignment. Depending on the focal length chosen, the effect of handshake can be quite different. For wide angle, it is small. However, for tele-photo lenses it is much larger. The global pre-alignment would ensure that the starting point of the tile-based alignment would be much more consistent.

**Comment by martin-marek** [comment]
Currently, the max. amount of shift between two frames is controlled by the "Search distance" parameter. Setting it to "high" means that the lowest resolution layer in the pyramid has width <32 and we're allowing up to ±1 shift at this resolution. I don't know whether this is enough or not for telephoto lenses. But if it's not enough, a trivial solution would be to simply increase the search distance.

Do you know if Google is doing any pre-alignment? Also, do you have an example where the current setup fails?

**Comment by chris-rank** [comment]
You are right. The strong downsizing in the lowest pyramid level should be sufficient to account for differences in displacement of the input burst images.

**Comment by chris-rank** [comment]
In my opinion this feature request can be closed as I do not see a need for it anymore. See discussion above.
