### ISSUE TITLE
[Feature Request] Automatically convert non-DNG raws to DNG

### ISSUE THREAD

**Issue by Alex-Vasile** [martin-marek/hdr-plus-swift#4]
Instead of having the user manually convert to DNG before running the app. It would be really convenient if the user could simply drag in non-DNG raw files and the app convert them to DNG and them process those DNGs.

**Comment by martin-marek** [comment]
This would be possible, for example through LibRaw. In fact, if you scroll though the commit history, you'll find that a previous version of Burst Photo [used](https://github.com/martin-marek/hdr-plus-swift/blob/b11b1a63ec6c5be95a023a76af868cd10efc18d9/burstphoto/libraw_utils.swift) LibRaw.

Unfortunately, in my personal testing, using LibRaw to read and write images resulted in degraded image quality. Moreover, you also loose some image metadata in the process.

I want Burst Photo to support all camera as well as possible, without any image quality / metadata loss. I believe that using a single standardized image format makes this much easier. I can rely on Adobe's DNG converter to convert almost all raw files perfectly, while relying on their SDK to work with the files perfectly.

If you are still interested in this, please feel free to fork Burst Photo and revert the switch that I made from LibRaw to DNG SDK. Alternatively, you could try using LibRaw [together](https://www.libraw.org/docs/API-datastruct-eng.html) with Adobe DNG SDK (see the `use_dng_sdk` flag).

**Comment by Alex-Vasile** [comment]
I see. Sorry for not being more explicit. I was referring to something else.

I am used to using dng->dng workflow through https://www.heliconsoft.com for focus stacking. They also use Adobe DNG's convertor, requiring you to specify the location to Adobe DNG convertor.

After it's specified, you can draw other raw format directly into the application and it will call the convertor to go from priopriotery raw to dng on the fly.

**Comment by martin-marek** [comment]
Oh, I see. That sounds like a great idea!

I won’t be able to work on this right now, but if I have more time in the future, I might try implementing this 🙂

**Comment by Alex-Vasile** [comment]
I may take a crack at it as soon as I get some time myself. Would you accept a PR for it if I do?

**Comment by martin-marek** [comment]
Perfect. That’s a great idea, but I assume the user will still need to grant some permissions to Burst Photo to access the Applications directory.

Also, I’m sorry in advance for the poor documentation of my code, I might try to clean it up slightly. If you want to chat about any of this in more detail, please feel free to reach me on [twitter](https://twitter.com/martinmarek1999).

**Comment by Alex-Vasile** [comment]
I don't have twitter, but i'm about half-way through this. I'll open a PR once I have *something* that's working. I'll send you an email (off your website) if I need any help in the meantime.

**Comment by martin-marek** [comment]
Awesome! Alright, please feel free to use the email (or this thread) if you have anything to discuss 🙂
