### ISSUE TITLE
[Feature request] Merging of images in the frequency domain

### ISSUE THREAD

**Issue by chris-rank** [martin-marek/hdr-plus-swift#9]
I would suggest to perform the merging of tiles in the frequency domain as suggested in the original paper. I already have a working function for this task implemented in your app. However, it requires some additional functionality that I have not yet implemented. First initial results already show a better image quality than the current implementation. One disadvantage of my current implementation is that it would only work with Bayer patterns. As the Fourier transformation is a little bit tricky, extension to generic patterns is a lot of work. Furthermore, the 2x2 pattern can be computed using SIMD instructions in Metal, which increases performance quite a bit. I would be more than happy to contribute here.

**Comment by chris-rank** [comment]
As an addition, there is a novel paper from Google with an improved version of the HDR+ algorithm, which uses a slightly adapted merging in the frequency domain:
http://graphics.stanford.edu/papers/night-sight-sigasia19/night-sight-sigasia19.pdf

The differences to the original implementation are small, but the authors claim a significant improvement of noise reduction and motion robustness. I have already checked the formulas and it will be easy to extend the functions I already have implemented.

**Comment by martin-marek** [comment]
Hi Chris, That sounds great! I would be happy to help. If you have any questions, please just post them here or email me – I'll try to respond quickly.
